# SonarCloud
sonar.projectKey=CauaSerpa_liderlux
sonar.organization=softhash

# Projeto
sonar.projectName=liderlux
sonar.projectVersion=1.0

# Código fonte
sonar.sources=application

# Exclusões
sonar.exclusions=\
vendor/**,\
system/**,\
docker/**,\
tests/**,\
assets/**,\
node_modules/**

# Encoding
sonar.sourceEncoding=UTF-8

# PHP
sonar.php.version=7.4

# Coverage (opcional)
sonar.php.coverage.reportPaths=coverage.xml