server {
    listen 80;
    server_name _;

    root /var/www;
    index index.php index.html;

    # ROUTER PRINCIPAL (CodeIgniter)
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # PHP HANDLER
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    # BLOQUEAR PASTAS SENSÍVEIS
    location ~* ^/(application|system|docker|\.env|db|sql) {
        deny all;
        return 403;
    }

    # BLOQUEAR ARQUIVOS OCULTOS
    location ~ /\.(env|git|htaccess) {
        deny all;
    }

    # SEGURANÇA EXTRA
    location ~* \.(log|sql|ini|conf)$ {
        deny all;
    }
}