name: CD Pipeline

on:
  push:
    branches:
      - staging
      - main

jobs:

  deploy-staging:

    if: github.ref == 'refs/heads/staging'

    runs-on: ubuntu-latest

    steps:

      - name: Deploy STAGING
        uses: appleboy/ssh-action@v1

        with:
          host: ${{ secrets.SERVER_HOST_STAGING }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}

          script: |

            cd /srv/liderlux-staging

            git pull origin staging

            export IMAGE_TAG=staging

            docker compose \
              -f compose/docker-compose.staging.yml \
              pull

            docker compose \
              -f compose/docker-compose.staging.yml \
              up -d


  deploy-production:

    if: github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest

    steps:

      - name: Deploy PROD
        uses: appleboy/ssh-action@v1

        with:
          host: ${{ secrets.SERVER_HOST_PROD }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}

          script: |

            cd /srv/liderlux-prod

            git pull origin main

            export IMAGE_TAG=latest

            docker compose \
              -f compose/docker-compose.prod.yml \
              pull

            docker compose \
              -f compose/docker-compose.prod.yml \
              up -d