name: CI Pipeline

permissions:
  contents: read
  packages: write

on:
  pull_request:
    branches:
      - develop
      - staging
      - main

  push:
    branches:
      - develop
      - staging

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"
          tools: composer

      - name: Composer cache
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache
          key: composer-${{ hashFiles('**/composer.lock') }}

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: PHP Syntax Check
        run: |
          find . \
            -name "*.php" \
            -not -path "./vendor/*" \
            -exec php -l {} \;

      - name: PHPUnit
        run: |
          if [ -f phpunit.xml ]; then
            vendor/bin/phpunit
          else
            echo "No PHPUnit configuration."
          fi

      - name: PHPStan
        run: |
          if [ -f vendor/bin/phpstan ]; then
            vendor/bin/phpstan analyse application --level=5
          else
            echo "PHPStan not installed."
          fi

      - name: Docker Build Validation
        run: |
          docker build \
            --build-arg APP_ENV=staging \
            -t liderlux:test \
            -f docker/php/Dockerfile .

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}