name: Full CI/CD Pipeline

on:
  pull_request:
    branches: [develop, hml, main]

  push:
    branches: [hml, main]

jobs:

  ci:
    name: CI + Sonar
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Install dependencies
        run: composer install --no-dev --prefer-dist

      - name: PHP syntax check
        run: find . -name "*.php" -not -path "./vendor/*" -exec php -l {} \;

      # SONAR
      - name: SonarQube Scan
        uses: sonarsource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

  deploy_hml:
    name: Deploy HML
    needs: ci
    if: github.ref == 'refs/heads/hml'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy HML via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /srv/liderlux-hml
            git pull origin hml
            docker compose down
            docker compose up -d --build

  deploy_main:
    name: Deploy MAIN
    needs: ci
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy Production
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /srv/liderlux-prod
            git pull origin main
            docker compose down
            docker compose up -d --build